server:
  port: 9527
spring:
  application:
    name: cloud-gateway
  cloud:
    gateway:
      routes:
        - id: payment_routh #路由的ID，没有固定规则但要求唯一，建议配合服务名
#          uri: http://localhost:8001   #匹配后提供服务的路由地址
          uri: lb://CLOUD-PAYMENT-SERVICE
          predicates:
            - Path=/payment/**   #断言,路径相匹配的进行路由
#            - After=2020-10-12T10:14:34.102+08:00[Asia/Shanghai]  #什么时间后放行，在此之前都会报/xxx无URI
            - Cookie=username,xxyy  #并且Cookie是username=xxyy才能访问

        - id: payment_routh2
          uri: https://www.baidu.com
          predicates:
            - Path=/**   #断言,路径相匹配的进行路由


eureka:
  instance:
    hostname: cloud-gateway-service
  client:
    service-url:
      register-with-eureka: true
      fetch-registry: true
      defaultZone: http://eureka1.server.mcsql.net:7001/eureka


