server:
  port: 80

spring:
  application:
    name: cloud-order-service

eureka:
  client:
    register-with-eureka: true
    fetchRegistry: true
    service-url:
      defaultZone: http://eureka1.server.mcsql.net:7001/eureka/,http://eureka2.server.mcsql.net:7002/eureka/ #集群


